"""ORCAState → ChatResponse Mapping Layer.

Owned by Dev 2 (Backend Platform).
Referenced by: backend/app/services/agent_run_service.py

Converts the completed LangGraph ORCAState dictionary into the stable
ChatResponse contract that the API returns to clients.

Design decisions
----------------
* Pure function — no I/O, no side-effects, easy to unit-test in isolation.
* Safe defaults everywhere: missing or None fields produce the most
  conservative output rather than an exception.
* Safety invariant: if ``risk_assessment`` is absent or None, the default
  recommendation status is UNKNOWN — never GO.  The service layer must never
  invent a positive safety clearance from absent evidence.
* Map layers and evidence items are returned as-is from state; the graph
  already normalises them to the correct Pydantic shapes.
"""

from __future__ import annotations

from typing import Any, Dict

from backend.app.contracts.chat import (
    ChatResponse,
    Confidence,
    ConfidenceLevel,
    Recommendation,
    RecommendationStatus,
)
from backend.app.contracts.mission import DecisionObject


def map_state_to_response(
    state: Dict[str, Any],
    run_id: str,
    conversation_id: str,
) -> ChatResponse:
    """Convert a completed ORCAState dict into a ChatResponse.

    Field mapping (ORCAState → ChatResponse):
        state["request_id"]       → run_id         (overridden by caller-supplied run_id)
        state["thread_id"]        → conversation_id (overridden by caller-supplied id)
        state["response"]         → answer
        state["risk_assessment"]  → recommendation
        state["confidence"]       → confidence
        state["evidence"]         → evidence
        state["map_layers"]       → map_layers
        state["trace"]            → trace
        state["warnings"]         → warnings
        state["suggested_followups"] → suggested_followups
        state["language"]         → language
        state["intent"]           → intent

    Safety defaults
    ---------------
    * ``recommendation``: absent → UNKNOWN status (never GO).
    * ``confidence``:     absent → LOW with explicit reason.
    * ``answer``:         absent → neutral holding message.
    * All list fields:    absent → empty list.

    Parameters
    ----------
    state:
        Completed ORCAState dictionary from ``run_orca_graph``.
    run_id:
        Unique per-request UUID generated by the route handler.
    conversation_id:
        Session UUID (from request or generated server-side).

    Returns
    -------
    ChatResponse
        Fully populated, schema-valid response ready for serialisation.
    """
    # ------------------------------------------------------------------
    # Recommendation — SAFETY INVARIANT: default to UNKNOWN, never GO
    # ------------------------------------------------------------------
    raw_risk = state.get("risk_assessment")
    recommendation: Recommendation
    if raw_risk is None:
        recommendation = Recommendation(
            status=RecommendationStatus.UNKNOWN,
            summary=(
                "Risk evaluation could not be completed. "
                "No authoritative assessment is available for this query."
            ),
            decisive_factors=["Insufficient data to evaluate departure safety."],
            non_decisive_factors=[],
            threshold_comparisons=[],
            next_action=(
                "Hold departure until authoritative marine and weather data "
                "can be retrieved and evaluated."
            ),
            warnings=state.get("warnings") or [],
        )
    elif isinstance(raw_risk, Recommendation):
        recommendation = raw_risk
    elif hasattr(raw_risk, "status") and hasattr(raw_risk, "recommended_action"):
        # Convert RiskAssessmentPayload to Recommendation
        recommendation = Recommendation(
            status=raw_risk.status,
            summary=raw_risk.summary,
            decisive_factors=raw_risk.decisive_factors,
            non_decisive_factors=getattr(raw_risk, "non_decisive_factors", []),
            threshold_comparisons=getattr(raw_risk, "threshold_comparisons", []),
            next_action=raw_risk.recommended_action,
            provenance=getattr(raw_risk, "provenance", []),
            evidence_ids=getattr(raw_risk, "evidence_ids", []),
            warnings=getattr(raw_risk, "warnings", []),
        )
    elif isinstance(raw_risk, dict):
        recommendation = Recommendation(**raw_risk)
    else:
        recommendation = Recommendation(
            status=RecommendationStatus.UNKNOWN,
            summary="Unrecognized risk evaluation format.",
            decisive_factors=["Internal schema conversion fallback."],
            next_action="Hold departure and verify with official coastal sources.",
        )

    # ------------------------------------------------------------------
    # Confidence
    # ------------------------------------------------------------------
    confidence: Confidence = state.get("confidence")  # type: ignore[assignment]
    if confidence is None:
        confidence = Confidence(
            level=ConfidenceLevel.LOW,
            reasons=["No evidence was gathered during this pipeline run."],
        )

    # ------------------------------------------------------------------
    # Answer / response text
    # ------------------------------------------------------------------
    answer: str = state.get("response") or (
        "ORCA was unable to synthesise a response for this query. "
        "Please try rephrasing or contact support."
    )

    # Every consumer receives the same canonical decision. Legacy clients
    # continue to use recommendation for backwards compatibility.
    raw_decision = state.get("decision_object")
    if raw_decision is not None:
        decision_object = raw_decision.model_dump() if hasattr(raw_decision, "model_dump") else raw_decision
    else:
        # confidence may arrive from ORCAState as a typed Confidence model or a
        # plain dict — handle both safely without calling .level on a dict.
        def _conf_level(c: Any) -> Any:
            if c is None:
                return ConfidenceLevel.LOW
            if hasattr(c, "level"):
                return c.level
            if isinstance(c, dict):
                return c.get("level", ConfidenceLevel.LOW)
            return ConfidenceLevel.LOW

        def _conf_reasons(c: Any) -> list:
            if c is None:
                return []
            if hasattr(c, "reasons"):
                return c.reasons
            if isinstance(c, dict):
                return c.get("reasons", [])
            return []

        _rec_conf = recommendation.confidence
        decision_object = DecisionObject(
            decision=recommendation.status,
            confidence=(_conf_level(_rec_conf) if _rec_conf is not None else _conf_level(confidence)),
            confidence_reasons=(_conf_reasons(_rec_conf) if _rec_conf is not None else _conf_reasons(confidence)),
            decisive_factor=recommendation.summary,
            supporting_factors=recommendation.decisive_factors,
            non_decisive_factors=recommendation.non_decisive_factors,
            constraints_applied=[],
            evidence=state.get("evidence") or [],
            inferences=[],
            provenance=recommendation.provenance,
            uncertainty=recommendation.warnings,
            alternatives=[],
            recommended_action=recommendation.next_action,
        ).model_dump()

    # ------------------------------------------------------------------
    # Assemble and return
    # ------------------------------------------------------------------
    return ChatResponse(
        run_id=run_id,
        conversation_id=conversation_id,
        assessment_id=state.get("observations", {}).get("assessment_id"),
        language=state.get("language") or "en",
        intent=state.get("intent") or "UNKNOWN",
        answer=answer,
        recommendation=recommendation,
        decision_object=decision_object,
        confidence=confidence,
        evidence=state.get("evidence") or [],
        map_layers=state.get("map_layers") or [],
        trace=state.get("trace") or [],
        warnings=state.get("warnings") or [],
        suggested_followups=state.get("suggested_followups") or [],
        agent_collaboration=state.get("agent_collaboration"),
        decision_object=state.get("decision_object"),
        decision_delta=state.get("decision_delta"),
        mission_state=state.get("mission_state"),
    )
