"""Data Catalogue Registry for India MarineWatch (§212).

Defines the First 30 authoritative datasets and services specified in the master
blueprint, complete with provider attribution, spatial bounds, temporal refresh cadence,
licensing, provenance, and active endpoint references.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


DATASETS_REGISTRY: List[Dict[str, Any]] = [
    {
        "id": "DS-01",
        "title": "INCOIS Ocean State Forecast (OSF)",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "Multi-parameter ocean state forecast: significant wave height, swell period/direction, surface currents, and sea surface temperature.",
        "spatial_coverage": "Indian Ocean / Arabian Sea / Bay of Bengal",
        "temporal_resolution": "3-hourly forecast up to 5 days",
        "update_cadence": "Every 6 hours",
        "license": "Government Open Data / Fair Use Attribution",
        "access_mode": "REST API / Open-Meteo High-Res Fallback",
        "provenance_url": "https://incois.gov.in/portal/osf",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-02",
        "title": "INCOIS Potential Fishing Zones (PFZ) Advisories",
        "provider": "INCOIS",
        "category": "Fisheries",
        "description": "Satellite-derived composite thermal front (NOAA/AVHRR/INSAT) and chlorophyll-a (Oceansat OCM) demarcating prospective pelagic fishing zones.",
        "spatial_coverage": "Coastal Indian EEZ (Sectors: Maharashtra, Goa, Gujarat, Karnataka, Kerala, etc.)",
        "temporal_resolution": "Daily advisory during non-monsoon periods",
        "update_cadence": "Daily at 06:00 IST",
        "license": "Public Service / Open Fisherfolk Advisory",
        "access_mode": "GeoJSON Vector Features / Spatial API",
        "provenance_url": "https://incois.gov.in/portal/pfz",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-03",
        "title": "INCOIS Predicted Astronomical Tide (PAT)",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "Harmonic tidal predictions for major and minor ports along Indian coastlines based on Survey of India and NHO tide constants.",
        "spatial_coverage": "All designated tidal stations on Indian coasts",
        "temporal_resolution": "5-minute harmonic curve / HW & LW extrema",
        "update_cadence": "Astronomical constant model (24/7 continuous)",
        "license": "Public Domain / Hydrographic Standard",
        "access_mode": "Native Harmonic Computation Engine",
        "provenance_url": "https://incois.gov.in/portal/pat",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-04",
        "title": "INCOIS Public ERDDAP Ocean Data Catalogue",
        "provider": "INCOIS",
        "category": "Research",
        "description": "Unified gridded and tabular scientific marine observations from buoys, Argo floats, HF radar, and coastal wave gauges.",
        "spatial_coverage": "Global Tropical Indian Ocean",
        "temporal_resolution": "Variable (Hourly to Monthly)",
        "update_cadence": "Near real-time",
        "license": "Open Access / Scientific Attribution",
        "access_mode": "ERDDAP REST / OPeNDAP",
        "provenance_url": "https://erddap.incois.gov.in/erddap",
        "status": "ONLINE",
        "quality_tier": "SCIENTIFIC",
    },
    {
        "id": "DS-05",
        "title": "INCOIS High-Resolution Sea Surface Temperature (SST)",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "Blended satellite and in-situ sea surface temperature maps with sub-kilometer coastal resolution.",
        "spatial_coverage": "North Indian Ocean",
        "temporal_resolution": "Daily mean",
        "update_cadence": "Daily",
        "license": "Public Data",
        "access_mode": "WMS / Gridded REST",
        "provenance_url": "https://incois.gov.in/OOS/sst",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-06",
        "title": "INCOIS Coastal Surface Ocean Currents",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "HF Radar and ROMS hydrodynamic model surface current vectors (speed and direction).",
        "spatial_coverage": "West Coast Konkan corridor & Gujarat Shelf",
        "temporal_resolution": "Hourly",
        "update_cadence": "Hourly",
        "license": "Public Data",
        "access_mode": "Vector Field / REST",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-07",
        "title": "INCOIS Significant Wave Height & Direction Forecast",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "WAVEWATCH III operational wave model output for swell and wind wave heights and peak periods.",
        "spatial_coverage": "Indian EEZ & offshore corridors",
        "temporal_resolution": "Hourly to 72 hours",
        "update_cadence": "Every 6 hours",
        "license": "Public Data",
        "access_mode": "REST / GeoJSON",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-08",
        "title": "INCOIS Swell Surge & Directional Spectra",
        "provider": "INCOIS",
        "category": "Ocean",
        "description": "Long-period Southern Ocean swell propagation warnings and nearshore swell surges (Kallakkadal warnings).",
        "spatial_coverage": "Southwest coast of India (Konkan, Malabar)",
        "temporal_resolution": "Event-driven bulletins",
        "update_cadence": "Continuous monitoring",
        "license": "Public Safety Bulletin",
        "access_mode": "Warning Feed / Hazard API",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-09",
        "title": "INCOIS Marine Heatwave (MAHAS) Tracker",
        "provider": "INCOIS",
        "category": "Environment",
        "description": "Automated thermal anomaly detection classifying Moderate, Strong, Severe, and Extreme marine heatwaves impacting coral and fisheries.",
        "spatial_coverage": "Arabian Sea & Bay of Bengal",
        "temporal_resolution": "Daily anomaly",
        "update_cadence": "Daily",
        "license": "Public Scientific Product",
        "access_mode": "WMS / REST",
        "provenance_url": "https://incois.gov.in/portal/mahas",
        "status": "ONLINE",
        "quality_tier": "SCIENTIFIC",
    },
    {
        "id": "DS-10",
        "title": "INCOIS Algal Bloom Information Service (ABIS)",
        "provider": "INCOIS",
        "category": "Environment",
        "description": "Harmful Algal Bloom (HAB) detections (Noctiluca scintillans, Trichodesmium) using satellite ocean color reflectance indices.",
        "spatial_coverage": "Northern Arabian Sea & coastal belts",
        "temporal_resolution": "Weekly composite",
        "update_cadence": "Weekly / Event-based",
        "license": "Public Data",
        "access_mode": "Vector Overlay",
        "provenance_url": "https://incois.gov.in/portal/abis",
        "status": "ONLINE",
        "quality_tier": "ADVISORY",
    },
    {
        "id": "DS-11",
        "title": "INCOIS Indian Tsunami Early Warning Centre (ITEWC)",
        "provider": "INCOIS",
        "category": "Hazards",
        "description": "National tsunami warning authority bulletins for bottom pressure recorder and coastal tide gauge anomalies.",
        "spatial_coverage": "Indian Ocean Rim",
        "temporal_resolution": "Real-time automated alerts",
        "update_cadence": "Real-time event driven",
        "license": "National Emergency Public Broadcast",
        "access_mode": "Hazard API",
        "provenance_url": "https://itewc.incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-12",
        "title": "INCOIS High Wave Alert & Ocean State Warnings",
        "provider": "INCOIS",
        "category": "Hazards",
        "description": "High wave warning polygons (wave height > 2.5m - 3.5m) advising artisanal non-motorized craft suspension.",
        "spatial_coverage": "Coastal districts of Maharashtra, Goa, Gujarat",
        "temporal_resolution": "Hourly warning windows",
        "update_cadence": "Twice daily",
        "license": "Public Safety Bulletin",
        "access_mode": "GeoJSON Alert Polygons",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-13",
        "title": "INCOIS Storm Surge & Coastal Inundation Warnings",
        "provider": "INCOIS",
        "category": "Hazards",
        "description": "Coupled hydrodynamic storm surge models predicting peak sea surge height above astronomical tide during cyclonic depressions.",
        "spatial_coverage": "Coastal talukas and vulnerable low-lying districts",
        "temporal_resolution": "Forecast track steps",
        "update_cadence": "Cyclone lifecycle",
        "license": "Disaster Management Broadcast",
        "access_mode": "Hazard API",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-14",
        "title": "INCOIS Ocean Observation Station Analytics (OOSA)",
        "provider": "INCOIS",
        "category": "Research",
        "description": "Telemetry feeds from moored buoys, wave rider buoys (WRB), and coastal automated weather stations.",
        "spatial_coverage": "Indian coastal stations",
        "temporal_resolution": "30-minute sampling",
        "update_cadence": "Hourly",
        "license": "Public Research Access",
        "access_mode": "REST / Observations API",
        "provenance_url": "https://incois.gov.in",
        "status": "ONLINE",
        "quality_tier": "SCIENTIFIC",
    },
    {
        "id": "DS-15",
        "title": "IMD Fishermen Coastal Warnings",
        "provider": "IMD",
        "category": "Hazards",
        "description": "Official India Meteorological Department marine bulletins for coastal fishermen warning against venturing into sea sectors.",
        "spatial_coverage": "All maritime coastal state sea belts",
        "temporal_resolution": "Daily / 5-day outlook",
        "update_cadence": "06:00 and 12:00 IST daily",
        "license": "Official Government Warning",
        "access_mode": "Hazard Feed / NLP Normalization",
        "provenance_url": "https://mausam.imd.gov.in/responsive/marine_forecast.php",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-16",
        "title": "IMD Port Warning Signals (Signals 1 to 11)",
        "provider": "IMD",
        "category": "Hazards",
        "description": "Standardized maritime port cautionary and danger flag signals (Signals 1-11) for Mumbai, Ratnagiri, Mormugao, and minor ports.",
        "spatial_coverage": "All registered Indian sea ports",
        "temporal_resolution": "Real-time state change",
        "update_cadence": "Immediate upon bulletin issue",
        "license": "Official Maritime Safety Notice",
        "access_mode": "REST / Port Warning API",
        "provenance_url": "https://mausam.imd.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-17",
        "title": "IMD Sea-Area Bulletins (South Arabian Sea & Central)",
        "provider": "IMD",
        "category": "Ocean",
        "description": "High-seas marine synoptic conditions, depressions, wind velocity, and visibility beyond coastal waters.",
        "spatial_coverage": "High seas of Arabian Sea & Bay of Bengal",
        "temporal_resolution": "12-hourly bulletins",
        "update_cadence": "Twice daily",
        "license": "Public Marine Weather Bulletin",
        "access_mode": "REST API",
        "provenance_url": "https://mausam.imd.gov.in",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-18",
        "title": "IMD Coastal Weather Forecast",
        "provider": "IMD",
        "category": "Ocean",
        "description": "Precipitation, gust wind speeds, squall alerts, and atmospheric pressure for Konkan, Goa, and coastal talukas.",
        "spatial_coverage": "West Coast maritime districts",
        "temporal_resolution": "3-hourly forecast",
        "update_cadence": "Four times daily",
        "license": "Public Weather Service",
        "access_mode": "REST API",
        "provenance_url": "https://mausam.imd.gov.in",
        "status": "ONLINE",
        "quality_tier": "OPERATIONAL",
    },
    {
        "id": "DS-19",
        "title": "GEBCO_2024 / GEBCO_2026 Global Bathymetric Grid",
        "provider": "GEBCO",
        "category": "Bathymetry",
        "description": "General Bathymetric Chart of the Oceans 15 arc-second terrain model providing bathymetric contours (0-2000m) along the Indian shelf.",
        "spatial_coverage": "Indian Subcontinent Continental Shelf & Deep Sea",
        "temporal_resolution": "Static biennial release",
        "update_cadence": "Biennial",
        "license": "GEBCO Open Data Policy (Attribution)",
        "access_mode": "Vector Contours / Point Elevation Engine",
        "provenance_url": "https://www.gebco.net",
        "status": "ONLINE",
        "quality_tier": "AUTHORITATIVE_TERRAIN",
    },
    {
        "id": "DS-20",
        "title": "ISRO Bhuvan Public Marine & Coastal Thematic Services",
        "provider": "Bhuvan / NRSC",
        "category": "Navigation",
        "description": "High-resolution satellite imagery base maps, coastal land use / land cover, and shoreline change layers.",
        "spatial_coverage": "All Indian coastal zones",
        "temporal_resolution": "Multi-year / Annual",
        "update_cadence": "Quarterly",
        "license": "Bhuvan Open Geoportal Policy",
        "access_mode": "WMS / WMTS Tile Service",
        "provenance_url": "https://bhuvan.nrsc.gov.in",
        "status": "ONLINE",
        "quality_tier": "GEOSPATIAL_BASEMAP",
    },
    {
        "id": "DS-21",
        "title": "OpenStreetMap Coastal Infrastructure Context",
        "provider": "OpenStreetMap",
        "category": "Navigation",
        "description": "Community-curated marine infrastructure: jetties, piers, breakwaters, coastal roads, and seamarks.",
        "spatial_coverage": "Indian Coastline",
        "temporal_resolution": "Continuous updates",
        "update_cadence": "Daily sync",
        "license": "ODbL (Open Database License)",
        "access_mode": "Vector Overlays / Tile Server",
        "provenance_url": "https://www.openstreetmap.org",
        "status": "ONLINE",
        "quality_tier": "REFERENCE",
    },
    {
        "id": "DS-22",
        "title": "Survey of India Administrative Coastal Boundaries",
        "provider": "Survey of India",
        "category": "Boundaries",
        "description": "Official State, District, and Taluka coastal boundaries and statutory baseline references.",
        "spatial_coverage": "National Coastal Boundary",
        "temporal_resolution": "Static official gazette",
        "update_cadence": "As revised by SOI",
        "license": "National Map Policy (Open Series Maps)",
        "access_mode": "GeoJSON Vector Layers",
        "provenance_url": "https://surveyofindia.gov.in",
        "status": "ONLINE",
        "quality_tier": "AUTHORITATIVE_LEGAL",
    },
    {
        "id": "DS-23",
        "title": "CAA Registered Coastal Aquaculture Farm Registry",
        "provider": "CAA",
        "category": "Aquaculture",
        "description": "Statutory registry of certified brackish-water shrimp and fish farms under the Coastal Aquaculture Authority Act, 2005.",
        "spatial_coverage": "Coastal talukas of Maharashtra, Goa, and coastal states",
        "temporal_resolution": "Quarterly register update",
        "update_cadence": "Quarterly",
        "license": "Statutory Public Registry",
        "access_mode": "REST / Vector Geometries",
        "provenance_url": "https://caa.gov.in",
        "status": "ONLINE",
        "quality_tier": "REGULATORY_COMPLIANCE",
    },
    {
        "id": "DS-24",
        "title": "CMFRI Marine Fishery Landings & Stock Statistics",
        "provider": "CMFRI",
        "category": "Fisheries",
        "description": "National marine fish catch estimates by species (pelagic, demersal, crustacean) and fishing effort across maritime states.",
        "spatial_coverage": "West Coast and East Coast Maritime States",
        "temporal_resolution": "Annual and quarterly landing estimates",
        "update_cadence": "Annual census release",
        "license": "ICAR Open Access / Academic Citation",
        "access_mode": "Tabular API / Analytics",
        "provenance_url": "https://www.cmfri.org.in",
        "status": "ONLINE",
        "quality_tier": "SCIENTIFIC",
    },
    {
        "id": "DS-25",
        "title": "CMFRI Marine Fish Landing Centres Registry",
        "provider": "CMFRI",
        "category": "Fisheries",
        "description": "Official spatial locations, craft capacities, major fishing gears, and infrastructure for 1,500+ landing centres across India.",
        "spatial_coverage": "Maharashtra, Goa, Gujarat, Karnataka, Kerala, Tamil Nadu, Andhra, Odisha, WB",
        "temporal_resolution": "CMFRI Census 2020 Baseline with live updates",
        "update_cadence": "Periodically updated",
        "license": "Open Government Data / Research Attribution",
        "access_mode": "REST / GeoJSON",
        "provenance_url": "https://www.cmfri.org.in",
        "status": "ONLINE",
        "quality_tier": "AUTHORITATIVE_REFERENCE",
    },
    {
        "id": "DS-26",
        "title": "NHO Online Navigational Electronic Chart Catalogue",
        "provider": "NHO",
        "category": "Navigation",
        "description": "National Hydrographic Office official navigational chart metadata, depth soundings index, and chart bounds.",
        "spatial_coverage": "Indian Navigational Waters (Charts 2011, 2016, 2078, etc.)",
        "temporal_resolution": "Edition cycles",
        "update_cadence": "Monthly updates",
        "license": "NHO Nautical Copyright Notice",
        "access_mode": "Metadata Reference API",
        "provenance_url": "https://hydrobharat.gov.in",
        "status": "ONLINE",
        "quality_tier": "NAUTICAL_STANDARD",
    },
    {
        "id": "DS-27",
        "title": "NHO Notices to Mariners (Navigational Warnings / NAVAREA VIII)",
        "provider": "NHO",
        "category": "Hazards",
        "description": "Fortnightly Notices to Mariners, sunken wrecks, drifting buoys, firing exercise warnings, and NAVAREA VIII radio advisories.",
        "spatial_coverage": "NAVAREA VIII (North Indian Ocean)",
        "temporal_resolution": "Fortnightly editions & Urgent NAVTEX broadcasts",
        "update_cadence": "Bi-weekly / Urgent alerts",
        "license": "Official Maritime Safety Information (MSI)",
        "access_mode": "Hazard Feed API",
        "provenance_url": "https://hydrobharat.gov.in",
        "status": "ONLINE",
        "quality_tier": "CRITICAL_SAFETY",
    },
    {
        "id": "DS-28",
        "title": "ISRO MOSDAC Open Marine Earth Observation Products",
        "provider": "ISRO MOSDAC",
        "category": "Research",
        "description": "Oceansat-3 (OCM-3) Chlorophyll-a and INSAT-3DR thermal infrared brightness temperatures for Arabian Sea ocean colour analysis.",
        "spatial_coverage": "Indian Subcontinent & Surrounding Seas",
        "temporal_resolution": "Daily passes",
        "update_cadence": "Every 24 hours",
        "license": "ISRO Open Data Policy",
        "access_mode": "Catalog REST / Raster Footprints",
        "provenance_url": "https://www.mosdac.gov.in",
        "status": "ONLINE",
        "quality_tier": "SCIENTIFIC",
    },
    {
        "id": "DS-29",
        "title": "data.gov.in Fisheries & Marine Sector Open Data",
        "provider": "data.gov.in / DoF",
        "category": "Fisheries",
        "description": "Pradhan Mantri Matsya Sampada Yojana (PMMSY) beneficiary statistics, ice plant subsidies, and craft motorization data.",
        "spatial_coverage": "District-level coastal aggregates",
        "temporal_resolution": "Annual fiscal releases",
        "update_cadence": "Bi-annual",
        "license": "National Data Sharing and Accessibility Policy (NDSAP)",
        "access_mode": "Open Data REST",
        "provenance_url": "https://data.gov.in",
        "status": "ONLINE",
        "quality_tier": "STATISTICAL",
    },
    {
        "id": "DS-30",
        "title": "Global Fishing Watch (GFW) Research & Public Good API",
        "provider": "Global Fishing Watch",
        "category": "Surveillance",
        "description": "Aggregated fishing vessel presence, apparent fishing hours, and vessel encounter events for noncommercial marine research.",
        "spatial_coverage": "High seas & Indian EEZ outer limits",
        "temporal_resolution": "Daily aggregated gridded heatmaps",
        "update_cadence": "Daily",
        "license": "Creative Commons CC-BY-SA 4.0 (Non-commercial)",
        "access_mode": "REST / Heatmap Tiles",
        "provenance_url": "https://globalfishingwatch.org",
        "status": "ONLINE",
        "quality_tier": "RESEARCH_SURVEILLANCE",
    },
]


def get_all_datasets(category: Optional[str] = None, provider: Optional[str] = None) -> List[Dict[str, Any]]:
    """Filter the 30 canonical datasets by category or provider."""
    results = DATASETS_REGISTRY
    if category:
        c_lower = category.lower()
        results = [d for d in results if d["category"].lower() == c_lower]
    if provider:
        p_lower = provider.lower()
        results = [d for d in results if d["provider"].lower() == p_lower]
    return results


def get_dataset_by_id(dataset_id: str) -> Optional[Dict[str, Any]]:
    """Lookup dataset by its canonical ID (e.g. DS-01)."""
    for d in DATASETS_REGISTRY:
        if d["id"].upper() == dataset_id.upper():
            return d
    return None
